### ISSUE TITLE
Reporte

### ISSUE THREAD

**Issue by christopheremv** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-christopheremv#2]
[reporteTextbox.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-christopheremv/files/6332613/reporteTextbox.pdf)

**Comment by Band-hi** [comment]
Practica: 92/100
Calificación: 18.4/20

-No contiene lista de figuras.
-Verificar la numeración de las figuras, y el titulo de las mismas.
-Faltan líneas en la conclusión.

**Comment by josealfredo79** [comment]
Hacer una practica mas detallada, para la próxima no se revisara por favor.
